### ISSUE TITLE
Dual concentric rotary encoder emulation feature?

### ISSUE THREAD

**Issue by AerialElectron** [DCSFlightpanels/dcs-bios-arduino-library#24]
I'm curious if anyone would be interested in a feature to emulate dual concentric rotary encoders using normal rotary encoders with built in push buttons? Concentric encoders are usually found on radio/navigation panels such as the A-10C's ILS and TACAN panels. These types of concentric encoders aren't always easy to source and can be rather expensive so I've found emulating them to be a great option for my own panels.

I've already written the code into the encoders header for my own purposes, but I can make a pull request if there is any interest. In terms of actual changes it's just another encoder class with a second message, second increment and decrement arguments, and another pin number for the button. The encoder defaults to the first message when rotated normally, but switches to the second message as long as the button is held down while rotating.

**Comment by talbotmcinnis** [comment]
Solution received from AerialElectron and has been merged into master to be part of the next release.
