### ISSUE TITLE
MatrixSwitches.h should either be bracketed by #ifdef block in the DcsBios.h, or included by default

### ISSUE THREAD

**Issue by icemarkom** [DCSFlightpanels/dcs-bios-arduino-library#46]
Currently, MatrixSwitches.h is [included from DcBios.h](https://github.com/DCSFlightpanels/dcs-bios-arduino-library/blob/b16c6b14e98b059fc745c80cf4ba800debcf0d96/src/DcsBios.h#L131), which leads casual observer to believe this include is always present. However, MatrixSwitches.h itself is [conditional on `USE_MATRIX_SWITCHES` being defined](https://github.com/DCSFlightpanels/dcs-bios-arduino-library/blob/b16c6b14e98b059fc745c80cf4ba800debcf0d96/src/internal/MatrixSwitches.h#L4).

This is suboptimal from the perspective of someone trying to understand the library. 

Two possible better solutions are:

- Bracket the `DcBios.h` include with ifdef block
- Include MatrixSwitches.h by default

**Comment by talbotmcinnis** [comment]
Agreed.  Will be done in 0.3.9.  Also added alternate and more standardized version DCSBIOS_USE_MATRIX_SWITCHES
