### ISSUE TITLE
Latest DCS Bios library "servo.h" library incompatible with ESP32 boards

### ISSUE THREAD

**Issue by lesthegringo** [DCSFlightpanels/dcs-bios-arduino-library#48]
I updated the DCS Bios library and now get the following error

f:\Users\LES\Documents\Arduino\libraries\Servo\src/Servo.h:77:2: error: #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."
 #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."

All ESP32 boards no cannot be used until this is corrected

**Comment by maciekish** [comment]
Have you tried using the official Servo library? Not sure if that helps but it was recently updated.

**Comment by talbotmcinnis** [comment]
0.3.9 will allow #define DCSBIOS_DISABLE_SERVO which will disable the servo library.
